const columns = [
  { name: "NAME", uid: "name" },
  { name: "ITEM", uid: "item" },
  { name: "PRICE", uid: "price" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];

const users = [
  {
    id: 1,
    name: "Tony Reichert",
    itemName: "some food",
    itemOrganization: "KSEA",
    itemPrice: 5.99,
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    itemName: "some food",
    itemOrganization: "KSEA",
    itemPrice: 5.99,
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    itemName: "some food",
    itemOrganization: "KSEA",
    itemPrice: 5.99,
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    itemName: "some food",
    itemOrganization: "KSEA",
    itemPrice: 5.99,
    status: "vacation",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    itemName: "some food",
    itemOrganization: "KSEA",
    itemPrice: 5.99,
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
];

export { columns, users };
